---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: visibility-hazelcast-manager
  labels:
    app: visibility-hazelcast-manager
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: visibility-hazelcast-manager
      zone: bb-hsec
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: visibility-hazelcast-manager
        zone: bb-hsec
    spec:
      containers:
        - name: visibility-hazelcast-manager
          image: hazelcast/management-center:3.12.5
          #    key: REGISTRY_CONNECTION_URL
          #    value: "http://visibility-confluent-registry:8081"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /visibility-hazelcast-manager
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: app-http
            - containerPort: 8080
              name: admin-http
            - containerPort: 8080
              name: app-https
            - containerPort: 8080
              name: admin-https
          imagePullPolicy: Always
          # readinessProbe defines when the pod is made available to load
          # balancer
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /visibility-hazelcast-manager
              port: 9443
              scheme: HTTP
            periodSeconds: 5
            initialDelaySeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
            requests:
              memory: "512Mi"
              cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: visibility-hazelcast-manager
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: visibility-hazelcast-manager

