---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: visibility-hazelcast-manager
  labels:
    app: visibility-hazelcast-manager
spec:
  minReadySeconds: 5
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: visibility-hazelcast-manager
      zone: bb-hsec
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: visibility-hazelcast-manager
        zone: bb-hsec
    spec:
      containers:
        - name: visibility-hazelcast-manager
          image: hazelcast/management-center:3.12.4
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 600
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          ports:
            - containerPort: 8080
              name: internal
            - containerPort: 8080
              name: external
            - containerPort: 8080
              name: tls
          imagePullPolicy: Always
          # readinessProbe defines when the pod is made available to load
          # balancer
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
            requests:
              memory: "512Mi"
              cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: visibility-hazelcast-manager
spec:
  ports:
      - name: http
        protocol: TCP
        port: 8080
  selector:
    app: visibility-hazelcast-manager

